workOrder/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',
         authentication_form=LoginForm), name='login'),
    path('', views.work_list, name='work_list'),
    path('core/<int:pk>/', views.work_detail, name='work_detail'),
    path('core/new/', views.work_create, name='work_create'),
    path('core/<int:pk>/edit/', views.work_update, name='work_update'),
    path('core/<int:pk>/delete/', views.work_delete, name='work_delete'),
    path('core/cetak/', views.cetak, name='cetak'),
    path('core/search/', views.work_search, name='work_search'),
    path('core/download/excel', views.download_excel, name='download_excel'),
]

workOrder/workOrder/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
# from .views import *

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    # path('work/', include('work.urls')),
]

workOrder/core/models.py
from django.db import models
from django.db.models.functions import Now


class Pekerjaan(models.Model):
    pekerjaan = models.CharField(max_length=255)

    class Meta:
        ordering = ('pekerjaan',)    # iterable
        verbose_name_plural = 'pekerjaan'

    def __str__(self):
        return self.pekerjaan


class Pengguna(models.Model):
    pengguna = models.CharField(max_length=255)

    class Meta:
        ordering = ('pengguna',)
        verbose_name_plural = 'pengguna'

    def __str__(self):
        return self.pengguna


class Status(models.Model):
    status = models.CharField(max_length=255)

    class Meta:
        ordering = ('status',)
        verbose_name_plural = 'status'

    def __str__(self):
        return self.status


class Pelaksana(models.Model):
    pelaksana = models.CharField(max_length=255)

    class Meta:
        ordering = ('pelaksana',)
        verbose_name_plural = 'pelaksana'

    def __str__(self):
        return self.pelaksana

# Create your models here.


class Report(models.Model):
    # nomor = models.IntegerField(default=0)
    jam = models.TimeField()
    tanggal = models.DateField()
    jenis_pekerjaan = models.ForeignKey(Pekerjaan, on_delete=models.CASCADE)
    user = models.ForeignKey(Pengguna, on_delete=models.CASCADE)
    pelaksana = models.ForeignKey(Pelaksana, on_delete=models.CASCADE)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    keterangan = models.TextField()

    class Meta:
        ordering = ["-tanggal", "-jam"]

workOrder/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Report

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))


INPUT_CLASS = 'w-full mx-10 py-4 px-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ('jam', 'tanggal', 'jenis_pekerjaan', 'user', 'pelaksana', 'status', 'keterangan')
        widgets = {
            'jam': forms.TimeInput(attrs={ 
                'type': 'time',
                'class': INPUT_CLASS 
            }),
            'tanggal': forms.DateInput(attrs={
                'type': 'date',
                'class': INPUT_CLASS
            }),
            'jenis_pekerjaan': forms.Select(attrs={
                'class': INPUT_CLASS
            }),
            'user': forms.Select(attrs={
                'class': INPUT_CLASS
            }),
            'pelaksana': forms.Select(attrs={
                'class': INPUT_CLASS
            }),
            'status': forms.Select(attrs={
                'class': INPUT_CLASS
            }),
            'keterangan': forms.Textarea(attrs={
                'class': INPUT_CLASS
            }),
        }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ('jenis_pekerjaan', 'user', 'pelaksana', 'status', 'keterangan')
        widgets = {
            'jenis_pekerjaan': forms.Select(attrs={
                'class': INPUT_CLASS
            }),
            'user': forms.Select(attrs={
                'class': INPUT_CLASS
            }),
            'pelaksana': forms.Select(attrs={
                'class': INPUT_CLASS
            }),
            'status': forms.Select(attrs={
                'class': INPUT_CLASS
            }),
            'keterangan': forms.Textarea(attrs={
                'class': INPUT_CLASS
            }),
        }

class DateSearchForm(forms.Form):
    jam = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

workOrder/core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Report, Status
from datetime import datetime, timedelta
# from item.models import Category, Item
from .forms import SignupForm

from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.http import HttpResponse
from .forms import NewItemForm, EditItemForm, DateSearchForm
from .models import Report


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })



@login_required
def work_list(request):
    reports = Report.objects.all()

    return render(request, 'core/task_list.html', {
        'reports': reports,
        })

@login_required
def work_search(request):
    global start_date, end_date, status_id
    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')
    # statuses = Status.objects.all()
    status_id = request.GET.get('status', None)
    data = Report.objects.all()

    if start_date and end_date:
        data = Report.objects.filter(tanggal__range=[start_date, end_date])
    # else:
    #     data = Report.objects.all()
    
    if status_id:
        data = data.filter(status__status__iexact=status_id)

    # status = Report.objects.filter(jam__range=[start_date, end_date])
    # if status:
    #     status = status.filter(Q(name__icontains=status))

    # penambahan pencarian untuk status pending, selesai, dan tahap rencana
    

    return render(request, 'core/task_search.html', {
        'data': data,
        'start_date':start_date,
        'end_date':end_date,
        'status_id':status_id,
        })

@login_required
def work_detail(request, pk):
    report = get_object_or_404(Report, pk=pk)
    return render(request, 'core/task_detail.html', {'reports': report})

@login_required
def work_create(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:work_list')
    else:
        form = NewItemForm()
    return render(request, 'core/task_form.html', {'form': form})

@login_required
def work_update(request, pk):
    report = get_object_or_404(Report, pk=pk)
    if request.method == 'POST':
        form = EditItemForm(request.POST, instance=report)
        if form.is_valid():
            form.save()
            return redirect('core:work_list')
    else:
        form = EditItemForm(instance=report)
    return render(request, 'core/task_form.html', {'form': form})


@login_required
def work_delete(request, pk):
    report = get_object_or_404(Report, pk=pk)
    if request.method == 'POST':
        report.delete()
        return redirect('core:work_list')
    return render(request, 'core/task_confirm_delete.html', {'report':report})

@login_required
def cetak(request):
    data = Report.objects.all()
    global start_date, end_date, status_id
    # penambahan start_date (untuk )
    # start_date = request.GET.get('start_date', None)
    # end_date = request.GET.get('end_date', None)
    # status_id = request.GET.get('status_id', None)
    # Lakukan operasi cetak dengan menggunakan start_date dan end_date
    if data == None:
        data = Report.objects.all()
    if start_date and end_date:
        data = Report.objects.filter(tanggal__range=[start_date, end_date])
    if status_id:
        data = data.filter(status__status__iexact=status_id)

    return render(request, 'core/cetak.html', {
        'data': data,
        'start_date': start_date,
        'end_date': end_date,
        'status_id':status_id
    })

import csv
import xlwt

def download_excel(request):
    # Retrieve filtering parameters
    global start_date, end_date, status_id
    # start_date = request.GET.get('start_date', None)
    # end_date = request.GET.get('end_date', None)
    # status_id = request.GET.get('status_id', None)

    # Apply filtering
    data = Report.objects.all()
    if start_date and end_date:
        data = data.filter(tanggal__range=[start_date, end_date])
    if status_id:
        data = data.filter(status__status__iexact=status_id)

    # Sort the data
    # data = data.order_by('tanggal')  # You can adjust the sorting criteria as per your requirement

    # Create Excel file
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="data.xls"'
    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Data')

    # Write headers
    headers = ['Jam', 'Tanggal', 'Jenis Pekerjaan', 'Unit', 'Pelaksana', 'Status', 'Keterangan']
    for col, header in enumerate(headers):
        ws.write(0, col, header)

    # ws.write(row_num + 1, 1, report.tanggal.strftime('%Y-%m-%d') if report.tanggal else '')
    # Write data rows
    for row_num, report in enumerate(data):
        ws.write(row_num + 1, 0, report.jam)
        ws.write(row_num + 1, 1, report.tanggal)
        ws.write(row_num + 1, 2, report.jenis_pekerjaan.pekerjaan)
        ws.write(row_num + 1, 3, report.user.pengguna)
        ws.write(row_num + 1, 4, report.pelaksana.pelaksana)
        ws.write(row_num + 1, 5, report.status.status)
        ws.write(row_num + 1, 6, report.keterangan)

    wb.save(response)
    return response

workOrder/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %}{% endblock title %} | WorkOrder</title>

    <script src="https://cdn.tailwindcss.com"></script>
    {% comment %} <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script> {% endcomment %}
</head>

<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200 bg-gray-800">
        <a href="/" class="text-2xl font-semibold text-white">RS PKU CEPU</a>

            {% if request.user.is_authenticated %}
            <a href="{% url "core:work_create" %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">
                Create New Task
            </a>
            
            {% else %}
            <a href="{% url 'core:signup' %}"
                class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign
                Up</a>
            <a href="{% url 'core:login' %}"
                class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-gray-700">Log
                In</a>
            {% endif %}

    </nav>
    <div class="px-6 py-2">
        {% block content%}

        {% endblock content%}
    </div>

    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-2 font-semibold text-gray-400 ">About</h3>
            <p class="mb-2 text-lg text-gray-500">Dibuat oleh Tim IT RS PKU Muhammadiyah Cepu</p>
        </div>

        {% comment %} <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

             <ul class="space-y-2">
                <li><a href="#" class="text-teal-500 text-lg hover:text-teal-700">About</a></li>
                <li><a href="{% url 'core:contact' %}" class="text-teal-500 text-lg hover:text-teal-700">Contact</a>
                </li>
                <li><a href="#" class="text-teal-500 text-lg hover:text-teal-700">Privacy policy</a></li>
                <li><a href="#" class="text-teal-500 text-lg hover:text-teal-700">Terms of use</a></li>
            </ul> {% 
        </div> {% endcomment %}

    </footer>
</body>

</html>

workOrder/core/templates/core/cetak.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <style>
            @media print {
            /* Custom styles for printing */
            .print-friendly-table th, .print-friendly-table td {
                padding: 0.5rem;
                font-size: 0.75rem; /* Adjust font size for printing */
            }
        }
    </style>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items-center bg-gray-300 text-white">
            <!-- Logo -->
            <div class="flex-shrink-0">
                {% comment %} <link rel="icon" href=" {% static "images/RSPKUCEPU.png" %}"> {% endcomment %}
                <img src="{% static "core/RSPKUCEPU.png" %}" alt="Logo Perusahaan" class="h-12">
            </div>
            <!-- Informasi Perusahaan -->
            <div class="px-auto ml-2 flex-shrink-0">
                <div class="text-4xl font-bold text-black">RS PKU MUHAMMADIYAH CEPU</div>
                <div class="text-base text-black">Jl.Ronggolawe No.137, Telp.(0296) 421727, Fax. (0296)424678 CEPU-58311</div>
                <div class="text-base text-black">Email : rspku_cepu@yahoo.co.id, Ijin Operasional : 449/221/2016, LARSI-SERT/50/II/2016</div>
            </div class="flex-shrink-0">
                <img src="{% static "core/LARSI.png" %}" alt="Logo Perusahaan" class="h-12">
            </div>
        
    </nav>    

    <table class="w-full border-collapse border border-gray-900 table-auto mx-auto">
        <thead>
            <tr>
                <th class="border border-gray-900 px-2 py-2">Jam</th>
                <th class="border border-gray-900 px-2 py-2">Tanggal</th>
                <th class="border border-gray-900 px-2 py-2">Jenis Pekerjaan</th>
                <th class="border border-gray-900 px-2 py-2">Unit</th>
                <th class="border border-gray-900 px-2 py-2">Pelaksana</th>
                <th class="border border-gray-900 px-2 py-2">Status</th>
                <th class="border border-gray-900 px-2 py-2">Keterangan</th>
                
                <!-- Add more headers for additional columns -->
            </tr>
        </thead>
        <tbody>
            {% for report in data %}
            <tr>
                <td class="border border-gray-900 px-2 py-1">{{ report.jam }}</td>
                <td class="border border-gray-900 px-2 py-1">{{ report.tanggal }}</td>
                <td class="border border-gray-900 px-2 py-1">{{ report.jenis_pekerjaan }}</td>
                <td class="border border-gray-900 px-2 py-1">{{ report.user }}</td>
                <td class="border border-gray-900 px-2 py-1">{{ report.pelaksana }}</td>
                <td class="border border-gray-900 px-2 py-1">{{ report.status }}</td>
                <td class="border border-gray-900 px-2 py-1">{{ report.keterangan }}</td>
            </tr>                    
            {% endfor %}
        </tbody>
    </table>
    
</body>
</html>

workOrder/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock title %}


{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h1 class="mb-12 text-2xl text-center">Tabel Report Pekerjaan</h1>
    <div class="flex justify-center">
        <table class="border-collapse border border-gray-200">
            <thead>
                <tr>
                    {% comment %} <th>ID</th> {% endcomment %}
                    <th class="border border-gray-200 p-4">Tanggal</th>
                    <th class="border border-gray-200 p-4">Jenis Pekerjaan</th>
                    <th class="border border-gray-200 p-4">Pengguna</th>
                    <th class="border border-gray-200 p-4">Pelaksana</th>
                    <th class="border border-gray-200 p-4">Status</th>
                    <th class="border border-gray-200 py-4 px-20">Keterangan</th>
                    <!-- Add more headers for additional columns -->
                </tr>
            </thead>
            <tbody>
                {% for report in reports %}
                <tr>
                    {% comment %} <td>{{ report.id }}</td> {% endcomment %}
                    <td class="border border-gray-200 p-4">{{ report.jam }}</td>
                    <td class="border border-gray-200 p-4">{{ report.jenis_pekerjaan }}</td>
                    <td class="border border-gray-200 p-4">{{ report.pengguna}}</td>
                    <td class="border border-gray-200 p-4">{{ report.pelaksana }}</td>
                    <td class="border border-gray-200 p-4">{{ report.status }}</td>
                    <td class="border border-gray-200 py-4 px-20">{{ report.keterangan }}</td>
                    
                    <!-- Render additional columns here -->
                </tr>                    
                {% endfor %}
            </tbody>
        </table>
    </div>
    
</div>

{% endblock content %}

workOrder/core/templates/core/task_confirm_delete.html
<!-- task_confirm_delete.html -->
{% extends "core/base.html" %}

{% block title %} Delete {% endblock title %}

{% block content %}
<div class="mt-2 px-6 py-8 bg-gray-100 rounded-xl">
        <h1 class="text-2xl font-bold ">Konfirmasi Penghapusan</h1><br>
    
    <p class="text-xl">Apakah kamu ingin menghapus data pada tanggal "{{ report.tanggal }}" dengan keterangan "{{ report.keterangan }}"</p>
    <form action="{% url 'core:work_delete' report.pk %}" method="post">
        {% csrf_token %}
        <button class="px-4 py-1 text-lg font-semibold bg-red-500 text-white rounded-md hover:bg-red-700" type="submit">Hapus</button>
    </form>
    <br>
    <a class="px-5 py-2 text-lg font-semibold bg-blue-500 text-white rounded-md hover:bg-blue-700" href="{% url 'core:work_list'%}">Batal</a>
</div>
{% endblock content %}

workOrder/core/templates/core/task_form.html
{% extends 'core/base.html' %}

{% block title %}{{title}}{% endblock title %}

{% block content %}
<h1 class="mb-6 text-3xl">{{title}}</h1>

<form action="." method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4 mx-10">
        {{ form.as_p }}
    </div>

    {% if from.errors or form.non_field_errors %}
    <div class="mb-3 p-6 bg-red-100 rounded-xl">
        {% for field in form %}
        {{ field.errors }}
        {% endfor %}

        {{form.non_field_errors}}
    </div>
    {% endif %}

    <button class="mx-10 mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>

</form>
{% endblock content %}

workOrder/core/templates/core/task_list.html
<!-- task_list.html -->

{% extends "core/base.html" %}

{% block title %} List {% endblock title %}

{% block content %}

<div class="mt-2 px-6 py-8 bg-gray-100 rounded-xl">
    <h1 class="mb-12 text-2xl text-center font-bold">Tabel Report Pekerjaan</h1>
    <form action="{% url 'core:work_search' %}" method="GET">
        <label for="start_date">Start Date:</label>
        <input type="date" id="start_date" class="rounded-xl border mx-2 my-1 p-2" name="start_date">
        <label for="end_date">End Date:</label>
        <input type="date" id="end_date" class="rounded-xl border mx-2 my-1 p-2" name="end_date">
        <label>Status Kategori:</label>
        <select name="status" class="rounded-xl border mx-2 my-1 p-2">
            <option value="">Semua Status</option>
            <option value="Selesai">Selesai</option>
            <option value="Pending">Pending</option>
            <option value="Tahap Rencana">Tahap Rencana</option>
        </select>
        <input type="submit" class="px-3 py-1 text-lg font-semibold bg-blue-500 text-white rounded-md hover:bg-blue-700" value="Filter">        
    </form>

    
    {% for model in daftar_model %}
        <!-- Tampilkan informasi model di sini -->
    {% endfor %}
    
    
    {% comment %} <button class="px-3 py-1 text-lg font-semibold bg-blue-500 text-white rounded-md hover:bg-blue-700" method="GET"><a href="{% url "core:cetak" %}">Cetak</a></button> {% endcomment %}
   
    <div class="flex justify-center mt-2">
        <table class="border-collapse border border-gray-200">
            <thead>
                <tr>
                    {% comment %} <th>ID</th> {% endcomment %}
                    <th class="border border-gray-200 p-4">Jam</th>
                    <th class="border border-gray-200 p-4">Tanggal</th>
                    <th class="border border-gray-200 p-4">Jenis Pekerjaan</th>
                    <th class="border border-gray-200 p-4">Unit</th>
                    <th class="border border-gray-200 p-4">Pelaksana</th>
                    <th class="border border-gray-200 p-4">Status</th>
                    <th class="border border-gray-200 p-4 w-auto">Keterangan</th>
                    <th> </th>
                    <th> </th>
                    <!-- Add more headers for additional columns -->
                </tr>
            </thead>
            <tbody>
                {% for report in reports %}
                <tr>
                    {% comment %} <td>{{ report.id }}</td> {% endcomment %}
                    <td class="border border-gray-200 p-4">{{ report.jam }}</td>
                    <td class="border border-gray-200 p-4">{{ report.tanggal }}</td>
                    <td class="border border-gray-200 p-4">{{ report.jenis_pekerjaan }}</td>
                    <td class="border border-gray-200 p-4">{{ report.user}}</td>
                    <td class="border border-gray-200 p-4">{{ report.pelaksana }}</td>
                    <td class="border border-gray-200 p-4 {% if report.status == 'Selesai' %}bg-green-500 text-white{% elif report.status == 'Pending' %}bg-red-500 text-white{% elif report.status == 'Tahap Rencana' %}bg-blue-500 text-white{% endif %}">{{ report.status }}</td>
                    <td class="border border-gray-200 p-4 w-auto text-justify">{{ report.keterangan }}</td>
                    <td class="border border-gray-200 px-1"><a href="{% url 'core:work_update' report.pk %}" class="px-4 py-1 text-base font-semibold bg-teal-500 text-white rounded-md hover:bg-teal-700">Edit</a></td>
                    <td class="border border-gray-200 px-1"><form action="{% url 'core:work_delete' report.pk %}" class="px-3 py-1 text-base font-semibold bg-red-500 text-white rounded-md hover:bg-red-700">
                        {% csrf_token %}
                        <button type="submit">Hapus</button>
                    </form></td>
                    
                    <!-- Render additional columns here -->
                </tr>                    
                {% endfor %}
            </tbody>
        </table>
    </div>
    
</div>


{% endblock content %}

workOrder/core/templates/core/task_search.html
<!-- task_list.html -->

{% extends "core/base.html" %}

{% block title %} List {% endblock title %}

{% block content %}

<div class="mt-2 px-6 py-8 bg-gray-100 rounded-xl">
    <h1 class="mb-12 text-2xl text-center font-bold">Tabel Report Pekerjaan</h1>
    <form action="{% url 'core:work_search' %}" method="GET">
        <label for="start_date">Start Date:</label>
        <input type="date" id="start_date" class="rounded-xl border mx-2 my-1 p-2" name="start_date">
        <label for="end_date">End Date:</label>
        <input type="date" id="end_date" class="rounded-xl border mx-2 my-1 p-2" name="end_date">
        <label>Status Kategori:</label>
        <select name="status" class="rounded-xl border mx-2 my-1 p-2">
            <option value="">Semua Status</option>
            <option value="Selesai">Selesai</option>
            <option value="Pending">Pending</option>
            <option value="Tahap Rencana">Tahap Rencana</option>
        </select>
        <input type="submit" class="px-3 py-1 text-lg font-semibold bg-blue-500 text-white rounded-md hover:bg-blue-700" value="Filter">        
    </form>

    {% comment %} Adding an excel button {% endcomment %}
    <button class="px-3 py-1 text-lg font-semibold bg-blue-500 text-white rounded-md hover:bg-blue-700" method="GET"><a href="{% url "core:download_excel" %}">Download Excel</a></button>
   
    <button class="px-3 py-1 text-lg font-semibold bg-blue-500 text-white rounded-md hover:bg-blue-700" method="GET"><a href="{% url "core:cetak" %}">Cetak</a></button>

    <div class="flex justify-center mt-2">
        <table class="border-collapse border border-gray-200">
            <thead>
                <tr>
                    {% comment %} <th>ID</th> {% endcomment %}
                    <th class="border border-gray-200 p-4">Jam</th>
                    <th class="border border-gray-200 p-4">Tanggal</th>
                    <th class="border border-gray-200 p-4">Jenis Pekerjaan</th>
                    <th class="border border-gray-200 p-4">Unit</th>
                    <th class="border border-gray-200 p-4">Pelaksana</th>
                    <th class="border border-gray-200 p-4">Status</th>
                    <th class="border border-gray-200 p-4 w-auto">Keterangan</th>
                    <th> </th>
                    <th> </th>
                    <!-- Add more headers for additional columns -->
                </tr>
            </thead>
            <tbody>
                {% for report in data %}
                <tr>
                    {% comment %} <td>{{ report.id }}</td> {% endcomment %}
                    <td class="border border-gray-200 p-4">{{ report.jam }}</td>
                    <td class="border border-gray-200 p-4">{{ report.tanggal }}</td>
                    <td class="border border-gray-200 p-4">{{ report.jenis_pekerjaan }}</td>
                    <td class="border border-gray-200 p-4">{{ report.user}}</td>
                    <td class="border border-gray-200 p-4">{{ report.pelaksana }}</td>
                    <td class="border border-gray-200 p-4">{{ report.status }}</td>
                    <td class="border border-gray-200 p-4 w-auto text-justify">{{ report.keterangan }}</td>
                    <td class="border border-gray-200 px-1"><a href="{% url 'core:work_update' report.pk %}" class="px-4 py-1 text-base font-semibold bg-teal-500 text-white rounded-md hover:bg-teal-700">Edit</a></td>
                    <td class="border border-gray-200 px-1"><form action="{% url 'core:work_delete' report.pk %}" class="px-3 py-1 text-base font-semibold bg-red-500 text-white rounded-md hover:bg-red-700">
                        {% csrf_token %}
                        <button type="submit">Hapus</button>
                    </form></td>
                    
                    <!-- Render additional columns here -->
                </tr>                    
                {% endfor %}
            </tbody>
        </table>
    </div>
    
</div>


{% endblock content %}